### PR TITLE
Upload firmware over the web interface, alternative to #68

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

**Comment by probonopd** [comment]
Why does this not compile? I have not even edited anything regarding "Temperature"...

**Comment by probonopd** [comment]
Also, when the user has configured the sketch to password protect the update functionality, then we should require a HTTP Basic Auth here.

**Comment by probonopd** [comment]
Thank you @GMagician :+1:

**Comment by probonopd** [comment]
Getting

```
<ok T:21.8 /0.0 T0:21.8 /0.0 @:0 B@:0#ok#
<echo:Unknown command: "UploadStart: old.bin"#wait more#
<ok#ok#
<echo:Unknown command: "sleep disable"#wait more#
<ok#ok#
>M105
<ok T:21.8 /0.0 T0:21.8 /0.0 @:0 B@:0#ok#
>M105
```

Why does the sketch think these strings are coming from the printer?

**Comment by probonopd** [comment]
The firmware does not get updated... we must be doing something wrong. Any clues?

**Comment by GMagician** [comment]
I'm not sure but avr mega needs to receive serial commands on boot to program firmware...

**Comment by chepo92** [comment]
I have one working example similar to this

**Comment by chepo92** [comment]
> Why does the sketch think these strings are coming from the printer?

Not the sketch, but the printer is replying you are doing a Sprintf (sending a command to the printer that doesn't understand)

**Comment by probonopd** [comment]
Indeed @chepo92, we need to replace the `Serial.printf()` and `Update.printError(Serial)` by something that "prints" to telnet.

**Comment by chepo92** [comment]
Actually this code is working for me, hint: if you have updated the esp firm through usb restart it before uploading through the web otherwise it will throw a "incorrect boostrap error"

**Comment by probonopd** [comment]
@chepo92 how is #104 different from this?

**Comment by chepo92** [comment]
With #104 i'm pushing to probonopd:upload-fw, so if you had merged that this PR would have been modified too (so you wouldn't have to do 32d98fc ). If there is a smarter way to do it pls tell me.

**Comment by probonopd** [comment]
I did 32d98fc to get your changes into this PR rather than having it in some other places, so that we can eventually merge this PR. Is this PR in the state that you intended?

I am not a Git wizard myself but generally I just use the GitHub web interface.

**Comment by chepo92** [comment]
Also I like the idea of #103, that you have another different page to upload firmware. I feel like trying to upload gcode using fiwmware upload and viceversa

**Comment by chepo92** [comment]
> 
> 
> I did [32d98fc](https://github.com/probonopd/WirelessPrinting/commit/32d98fc6c366b879316f4dac273b72d7f6b44710) to get your changes into this PR rather than having it in some other places, so that we can eventually merge this PR.

With #104 that would have been automatically done (changes on probonopd:upload-fw would be reflected in this PR while it's open. But never mind :) 
 
>  Is this PR in the state that you intended?

I think yes

> I am not a Git wizard myself but generally I just use the GitHub web interface.

The problem is that in GH web I can't compile, check and upload in my local hardware, Also I could make errors copy pasting things (and more key pressing involved)

**Pull request merged**
