### PR TITLE
M115 send n times for autobaud

### PR DESCRIPTION
**Pull request by chepo92**

### CODE REVIEW

**Comment by probonopd** [comment]
If you are not aware, every build that has a green checkmark has build artifacts (firmware) which you can donwload for testing. 
* Click on the green checkbox
* Click on "Details"
*Click on "Raw Log"
* Scroll to the bottom, find https://transfer.sh/10kbVS/ESP8266WirelessPrintAsync_d1_mini_413711c.bin (in this example)

**Comment by probonopd** [comment]
(Still) __works for me__. Ready for merging @chepo92 @GMagician?

**Comment by chepo92** [comment]
Nope

**Comment by chepo92** [comment]
It is doing this (info): 
```
Last command sent: M115
Last received response: Cap:AUTOLEVEL:0Cap:Z_PROBE:0Cap:LEVELING_DATA:0Cap:BUILD_PERCENT:0Cap:SOFTWARE_POWER:0Cap:TOGGLE_LIGHTS:0Cap:CASE_LIGHT_BRIGHTNESS:0Cap:EMERGENCY_PARSER:0Cap:AUTOREPORT_SD_STATUS:0Cap:THERMAL_PROTECTION:1ok


```

and telnet: 

```
<FIRMWARE_NAME:Marlin 1.1.9 (Github) SOURCE_CODE_URL:https://github.com/MarlinFi                                                          rmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:MMK HB EXTRUDER_COUNT:1 UUID:ced                                                          e2a2f-41a2-4748-9b12-c55c62f367ff#wait more#
<ap:SERIAL_XON_XOFF:0#wait more#
<T_TEMP:1#wait more#
<Cap:PROGRESS:0#wait more#
<Cap:PRINT_JOB:1#autotemp#
<Cap:AUTOLEVEL:0#wait more#
<Cap:Z_PROBE:0#wait more#
<Cap:LEVELING_DATA:0#wait more#
<Cap:BUILD_PERCENT:0#wait more#
<Cap:SOFTWARE_POWER:0#wait more#
<Cap:TOGGLE_LIGHTS:0#wait more#
<Cap:CASE_LIGHT_BRIGHTNESS:0#wait more#
<Cap:EMERGENCY_PARSER:0#wait more#
<Cap:AUTOREPORT_SD_STATUS:0#wait more#
<Cap:THERMAL_PROTECTION:1#wait more#
<ok#ok#
Connecting at 500000
>M115

```

(Look at <Cap:PRINT_JOB:1#autotemp# )

**Comment by probonopd** [comment]
Looks good, other than

```
<FIRMWARE_NAME:Marlin 1.1.9 (Github) SOURCE_CODE_URL:https://github.com/MarlinFi                                                          rmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:MMK HB EXTRUDER_COUNT:1 UUID:ced                                                          e2a2f-41a2-4748-9b12-c55c62f367ff#wait more#
<ap:SERIAL_XON_XOFF:0#wait more#
```
Is that really cropped like this or is this just a copy-and-paste effect

**Comment by chepo92** [comment]
<FIRMWARE_NAME:Marlin 1.1.9 (Github) SOURCE_CODE_URL:https://github.com/MarlinFi                                                          rmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:MMK HB EXTRUDER_COUNT:1 UUID:ced                                                          e2a2f-41a2-4748-9b12-c55c62f367ff#wait more#
<ap:SERIAL_XON_XOFF:0#wait more#
<T_TEMP:1#wait more#


> 
> 
> Looks good, other than
> 
> ```
> <FIRMWARE_NAME:Marlin 1.1.9 (Github) SOURCE_CODE_URL:https://github.com/MarlinFi                                                          rmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:MMK HB EXTRUDER_COUNT:1 UUID:ced                                                          e2a2f-41a2-4748-9b12-c55c62f367ff#wait more#
> <ap:SERIAL_XON_XOFF:0#wait more#
> ```
> 
> Is that really cropped like this or is this just a copy-and-paste effect

cp effect, but the "C" is still missing  <ap:SERIAL_XON_XOFF:0#wait more#

**Comment by chepo92** [comment]
My lastest commit 3e087b7 is working with marlin 1.1.9

**Pull request merged**
