### PR TITLE
Implement download

### PR DESCRIPTION
**Pull request by GMagician**

### CODE REVIEW

**Comment by GMagician** [comment]
Address #78

**Comment by probonopd** [comment]
When I click on the download link i get the correct file size and MIME type, but then it crashes the sketch, which is rebooting the ESP.

screenshot_2019-03-02_15-42-05

**Comment by probonopd** [comment]
We could also send a header with the correct file name.

**Comment by GMagician** [comment]
the problem may be:
1) file closed too early
2) send will not return untill all done raising wd

**Comment by probonopd** [comment]
Unfortunately it is still crashing.

**Comment by probonopd** [comment]
Maybe  the internal watchdog will trigger a force reset because it thinks something is stuck?

**Comment by GMagician** [comment]
I splitted read by 1Kb chunks...

**Comment by probonopd** [comment]
That is doing the trick :+1: downloading at 20 KB/sec

**Comment by GMagician** [comment]
No I was adding filename

**Comment by probonopd** [comment]
Maybe we should keep [WIP] in the title of PRs until they are ready for being merged. Some projects do this

**Comment by GMagician** [comment]
Now its completed!

**Comment by probonopd** [comment]
It works, and it is also much faster now :+1:

**Comment by probonopd** [comment]
Continues in https://github.com/probonopd/WirelessPrinting/pull/92

**Comment by GMagician** [comment]
yes 2kb x chunk

**Pull request merged**
