### PR TITLE
ESP32 SPIFFS

### PR DESCRIPTION
**Pull request by GMagician**
This is starting part for implementing SPIFFS on ESP32...to check since I don't have ESP32

### CODE REVIEW

**Comment by probonopd** [comment]
When using this, does compiling the sketch for ESP32 work for you?

**Comment by GMagician** [comment]
I don't have installed esp32 libraries...

**Comment by probonopd** [comment]
Only one way to find out... let's try it

**Comment by probonopd** [comment]
Any clue about what may be going wrong here?

**Comment by GMagician** [comment]
it seems a lot of things are missing to let it be compiled for ESP32...

**Comment by GMagician** [comment]
The problem now is sdfat...it doens't support ESP32...

**Comment by probonopd** [comment]
ESP32 has its [native SD implementation](https://github.com/espressif/arduino-esp32/tree/master/libraries/SD); so more IFDEFs may be needed

**Comment by GMagician** [comment]
@probonopd it seems that something related to "web flash" is not supported in esp32 (update.runasync)

**Comment by probonopd** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer/issues/455#issuecomment-451609200

**Pull request merged**
