### PR TITLE
Add AsyncElegantOTA

### PR DESCRIPTION
**Pull request by ayushsharma82**
Add AsyncElegantOTA to perform OTA's Elegantly.

### CODE REVIEW

**Comment by probonopd** [comment]
Cool! 👍 Build is using the library now but there is still a compile error, please see the build log.

**Comment by ayushsharma82** [comment]
@probonopd  Right. I am working on a Fix.

**Comment by ayushsharma82** [comment]
@probonopd  It's saying `sendCommands` and `receiveCommands` are not declared?

https://github.com/ayushsharma82/WirelessPrinting/blob/master/ESP8266WirelessPrintAsync/ESP8266WirelessPrintAsync.ino#L891

Is that due to, functions declared under it?

**Comment by probonopd** [comment]
Looks like it.

**Comment by ayushsharma82** [comment]
@probonopd  Passed ESP8266 Build. ESP32 Build is causing some problem due to a script error in travis.yml . Please take a look.

**Comment by probonopd** [comment]
Maybe need to add `#include <Hash.h>` for ESP32. Seems to be a known issue:
* https://github.com/me-no-dev/ESPAsyncWebServer/issues/46
* https://github.com/me-no-dev/ESPAsyncWebServer/issues/327
* Last resort? https://github.com/bbx10/Hash_tng

**Comment by probonopd** [comment]
So this was not sufficient, still getting `ESP8266WirelessPrintAsync:9:20: error: Hash.h: No such file or directory` for ESP32. Maybe @me-no-dev knows?

**Comment by ayushsharma82** [comment]
Maybe you can figure this out.. i have no idea why it's not getting Hash.h

**Comment by probonopd** [comment]
Yes, but give me some time. Thanks until here, great PR

**Comment by ayushsharma82** [comment]
No problem.

**Comment by probonopd** [comment]
Yay! Looks like we have a winner.
Do they work for you, including OTA?

* https://transfer.sh/eC7i8/ESP8266WirelessPrintAsync_d1_mini_1dad4cb.bin
* https://transfer.sh/aKQpF/ESP8266WirelessPrintAsync_esp32_1dad4cb.bin
(Links available for 14 days)

**Comment by ayushsharma82** [comment]
@probonopd  I will it check today. 👍

**Comment by ayushsharma82** [comment]
Surprisingly, It compiles for me without that library.Try latest release of ESP32 Arduino Core.

**Comment by ayushsharma82** [comment]
I just checked the build logs. It is using 75% of Sketch space. Is there any space left of an OTA  🤦‍♂ .

**Comment by probonopd** [comment]
On the ESP32, getting

failed

but the update nevertheless seems to have worked. I have the updated firmware on the machine afterwards.

**Comment by probonopd** [comment]
Also, we need a link to `/update` from the main page so that one finds the page.

**Comment by ayushsharma82** [comment]
I will update ElegantOTA Webpage by tomorrow.  Thanks for testing.

**Comment by ayushsharma82** [comment]
Fixed webpage and tested on my ESP32. 
There is a travis script error for esp8266. @probonopd  please take a look.

Thanks!

**Comment by probonopd** [comment]
Don't know why it is failing, perhaps an intermittent issue?

**Comment by ayushsharma82** [comment]
I think it's failing due to some change in esp8266 arduino package.json
which arduino gets for the board manager.

**Comment by probonopd** [comment]
http://arduino.esp8266.com/stable/package_esp8266com_index.json gives in Firefox:

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by ayushsharma82** [comment]
Yup. It's a problem with their package.json

Can you test it by compiling on your pc for esp8266?
We can merge, if it compiles successfully.

**Comment by probonopd** [comment]
I never compile anything locally. It needs to pass the automated builds...

**Comment by ayushsharma82** [comment]
Okay. Then we can wait till esp8266 arduino core fixes itself.

**Comment by probonopd** [comment]
The build is working now. Do we not get the red arrow anymore? (Couldn't test myself yet)

**Comment by ayushsharma82** [comment]
Nope. I have updated AsyncElegantOTA. It shows the `Successful` when updated.
ESP32 was resetting before the AsyncWebServer had actually sent the response in background. So i have added a 1 second delay in which it will send the response back to the webpage.

**Comment by ayushsharma82** [comment]
Can we merge it now?

**Comment by probonopd** [comment]
I did not have a chance to test it on ESP8266 and ESP32 yet, sorry. Do we have a link to the firmware update page from the main frontpage?

**Comment by ayushsharma82** [comment]
I will add that

**Comment by ayushsharma82** [comment]
Done

**Comment by probonopd** [comment]
If you have successfully tested updating on ESP8266 and ESP32 hardware with no red arrows or other errors, then I think we can merge?

**Comment by ayushsharma82** [comment]
Sure.

**Pull request merged**
