### PR TITLE
Add some config settings and flash status report

### PR DESCRIPTION
**Pull request by chepo92**
Add chip select and for increased compatibility with other boards
Add compatibility with slow micro sd shields 
Add a on screen status showing if the SD or SPIFFS is used

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you. What is wrong with using `SS`? It should be defined by the board. https://www.arduino.cc/en/Reference/SDbegin

**Comment by chepo92** [comment]
> 
> 
> > Add chip select and for increased compatibility with other boards
> 
> Thank you. What is wrong with using `SS`? It should be defined by the board. https://www.arduino.cc/en/Reference/SDbegin
> 
Yes it should be defined, I was struggling with some SD cards not working with the call SD.begin(SS, clock) I thought it was related to CS pin not defined correctly. I'll try with default SS and delete CS definition.

> > Add compatibility with slow micro sd shields
> 
> Did you encounter it helped in your case? Or is it just a hypothesis?
> (How do you know that it helped?)
> 
SD.begin(SS, clock) with clock: 50M doesn't work with a type of my microSD shields (tried other SD cards and adapter combinations),  I also tried library examples, only SD.begin(SS) works. My hypothesis is that the IC on the SD adapter is not fast enough (¿try slower speed?). 

> > Add a on screen status showing if the SD or SPIFFS is used
> 
> Well, so far SPIFFS is used when "SD" is not printed on the screen. 
I did'nt know that until I saw "SPIFFS" on screen, and that's how I started my quest to make the SD adapter work.

**Comment by chepo92** [comment]
Updated the PR

**Comment by probonopd** [comment]
> My hypothesis is that the IC on the SD adapter is not fast enough

You have an IC on the SD adapter? Interesting... I thought SD adapters only have passive components (most notably, a capacitor - which seems to make a big difference for reliability)

**Comment by GMagician** [comment]
Excuse me, when useFastSD clock is 50MHz...isn't max SD card clock 25MHz?

https://stackoverflow.com/questions/6195099/sd-card-interfacing-using-spi

> The SD card specifications state a maximum clock frequency of 25MHz

**Comment by chepo92** [comment]
@GMagician welcome to 2019! that thread is from 7 years ago :D (and has no reference)
From Panasonic site UHS-I can use up to 208 MHz: 
https://panasonic.net/cns/sdcard/industrial_sd/performance.html

**Comment by GMagician** [comment]
@chepo92 good year to you and thanks for quick answer.
I'm doing some reworks on this code this is why I asked this
done:
   - support pause
   - till 6 extruders supported
   - add queue for commands
   - support Cap:AUTOREPORT_TEMP

todo:
  - printer start autodetect (remove 3 second delay on start)
  - serial baud autodetect
  - sd clock autodetect

**Comment by chepo92** [comment]
Nice, i'll take a look to your repo, 
I also want to update the code to match actual octoprint behavior and to be compatible with last version of cura.

**Comment by GMagician** [comment]
I put code now on my repo...at the moment it's not working for sure (missing starting m115 handling..a fake response is hardcoded) but everything else should work

**Pull request merged**
