### PR TITLE
Some missing fix

### LINKED ISSUE #62: Cura does not show temperatures
Yay, uploading and printing from Cura 3.5 works for me in 5d4ba19.

Cura does not show the temperatures. The progress indicator shows progress though!

During heating, getting on telnet:

```
me@host:~$ telnet 192.168.0.27
Trying 192.168.0.27...
Connected to 192.168.0.27.
Escape character is '^]'.
< #TIMEOUT#
> G1 X113.952 Y90.635 E0.11222
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X114.542 Y90.533 E0.13462
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X115.009 Y90.509 E0.15212
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X134.991 Y90.51 E0.8998
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X135.59 Y90.55 E0.92226
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X136.177 Y90.669 E0.94467
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> G1 X136.744 Y90.865 E0.96712
< New line but nothing to do with it
```

During printing, getting 

```
  free heap RAM: 35656

> G1 X128.599 Y97.201 E866.00573
< ok

  1541733
  free heap RAM: 35656

> M105
< ok T:198.9 /200.0 B:60.0 /60.0 T0:198.9 /200.0 @:81 B@:72

  1541744
  free heap RAM: 35608

> G0 F7200 X128.599 Y96.901
```

`/api/printer` does not show the correct values:

```
{
  "state": {
    "text": "Printing",
    "flags": {
      "operational": true,
      "paused": false,
      "printing": true,
      "pausing": false,
      "cancelling": false,
      "sdReady": false,
      "error": false,
      "ready": true,
      "closedOrError": false
    }
  },
  "temperature": {
    "tool0": {
      "actual": 0.0,
      "target": 0.0,
      "offset": 0
    },
    "bed": {
      "actual": 0.0,
      "target": 0.0,
      "offset": 0
    }
  },
  "sd": {
    "ready": false
  }
}
```

### PR DESCRIPTION
**Pull request by GMagician**
Fix #62 and some fixes chepo92 sent and not merged in time

### CODE REVIEW

**Comment by probonopd** [comment]
During the heating phase I get

```
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> M105
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> M105
< New line but nothing to do with it
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> M105
< New line but nothing to do with it
< New line but nothing to do with it
< #TIMEOUT#
> M105
< New line but nothing to do with it
< New line but nothing to do with it
...
```
During printing, getting

```
> G1 F1800 X115.3 Y114.7 E104.32745
< 
  338948
  free heap RAM: 35672

> G1 X115.3 Y95.3 E104.81139
< 
  339164
  free heap RAM: 35672

> G1 X134.7 Y95.3 E105.29532
< 
  339197
  free heap RAM: 35672

> G1 X134.7 Y114.7 E105.77926
< 
  339372
  free heap RAM: 35672

> G0 F7200 X134.4 Y114.7
< 
  339405
  free heap RAM: 35672

> G0 X134.11 Y114.11
< 
  339541
  free heap RAM: 35672

> G1 F1800 X115.89 Y114.11 E106.23376
< 
  339574
  free heap RAM: 35672

> G1 X115.89 Y95.89 E106.68826
< 
  339670
  free heap RAM: 35672

> G1 X134.11 Y95.89 E107.14276
< 
  339703
  free heap RAM: 35672

> G1 X134.11 Y114.11 E107.59726
< 
  339759
  free heap RAM: 35672

> M105
< 
  339769
  free heap RAM: 35672

> G0 F7200 X133.839 Y113.082
< 
  339792
  free heap RAM: 35672

> G1 F1800 X133.081 Y113.839 E107.62398
< 
  339807
  free heap RAM: 35672

> G0 F7200 X132.233 Y113.839
< 
  340022
  free heap RAM: 35672

> G1 F1800 X133.839 Y112.234 E107.68062
< 
  340036
  free heap RAM: 35672

> G0 F7200 X133.839 Y111.385
< 
  340047
  free heap RAM: 35672

> G1 F1800 X131.384 Y113.839 E107.76721
< 
  340700
  free heap RAM: 35672

> G0 F7200 X130.536 Y113.839
< 
  341383
  free heap RAM: 35672

> G1 F1800 X133.839 Y110.537 E107.88371
< 
  342013
  free heap RAM: 35672

> G0 F7200 X133.839 Y109.688
< 
  342669
  free heap RAM: 35672

> G1 F1800 X129.687 Y113.839 E108.03017
< 
  342686
  free heap RAM: 35672

> G0 F7200 X128.839 Y113.839
< 
  342713
  free heap RAM: 35672

> G1 F1800 X133.839 Y108.839 E108.20656
< 
  343330
  free heap RAM: 35672

> G0 F7200 X133.839 Y107.991
< 
  343947
  free heap RAM: 35672

> G1 F1800 X127.99 Y113.839 E108.41288
< 
  344564
  free heap RAM: 35672

> G0 F7200 X127.142 Y113.839
< 
  345181
  free heap RAM: 35672

> G1 F1800 X133.839 Y107.142 E108.64913
< 
  345221
  free heap RAM: 35672

> G0 F7200 X133.839 Y106.294
< 
  345264
  free heap RAM: 35672

> M105
< 
  345274
  free heap RAM: 35672

> G1 F1800 X126.293 Y113.839 E108.91532
< 
  345298
  free heap RAM: 35672

> G0 F7200 X125.444 Y113.839
< 
  345381
  free heap RAM: 35672

> G1 F1800 X133.839 Y105.445 E109.21146
< 
  345415
  free heap RAM: 35672

> M105
< 
  345425
  free heap RAM: 35672

> G0 F7200 X133.839 Y104.597
< 
  345538
  free heap RAM: 35672

> G1 F1800 X124.596 Y113.839 E109.53751
< 
  345573
  free heap RAM: 35672

> G0 F7200 X123.747 Y113.839
< 
  345736
  free heap RAM: 35672

> M105
< 
  345746
  free heap RAM: 35672

> G1 F1800 X133.839 Y103.748 E109.89352
< 
  345771
  free heap RAM: 35672

> G0 F7200 X133.839 Y102.9
< 
  345980
  free heap RAM: 35672

> G1 F1800 X122.899 Y113.839 E110.27944
< 
  346008
  free heap RAM: 35672

> G0 F7200 X122.05 Y113.839
< 
  346252
  free heap RAM: 35672

> G1 F1800 X133.839 Y102.051 E110.69531
< 
  346287
  free heap RAM: 35672

> G0 F7200 X133.839 Y101.203
< 
  346570
  free heap RAM: 35672

> G1 F1800 X121.202 Y113.839 E111.1411
< 
  346605
  free heap RAM: 35672

> G0 F7200 X120.353 Y113.839
< 
  346929
  free heap RAM: 35672

> G1 F1800 X133.839 Y100.354 E111.61683
< 
  346964
  free heap RAM: 35672

> G0 F7200 X133.839 Y99.506
< 
  347329
  free heap RAM: 35672

> G1 F1800 X119.505 Y113.839 E112.12249
< 
  347363
  free heap RAM: 35672

> G0 F7200 X118.656 Y113.839
< 
  347768
  free heap RAM: 35672

> G1 F1800 X133.839 Y98.657 E112.65809
< 
  348279
  free heap RAM: 35672

> G0 F7200 X133.839 Y97.809
< 
  348292
  free heap RAM: 35672

> G1 F1800 X117.808 Y113.839 E113.22361
< 
  348802
  free heap RAM: 35672
```

**Comment by probonopd** [comment]
`/info` says `AUTOREPORT_TEMP: false Enabled: false`

**Comment by GMagician** [comment]
do you have it `AUTOREPORT_TEMP` enabled in your firmware?

**Comment by GMagician** [comment]
if you execute a M115 in repetier is there a Cap:AUTOREPORT_TEMP

**Comment by probonopd** [comment]
> do you have `AUTOREPORT_TEMP` enabled in your firmware?

No. https://github.com/prusa3d/Prusa-Firmware/tree/MK2 does not have that feature.

**Comment by GMagician** [comment]
Ok, this should fix M105 but I think you don't have also "report busy while  eating"

**Comment by GMagician** [comment]
Wait merge.. I want to give a different approach to M109 timeoutsss

**Comment by GMagician** [comment]
This should be complete fix for timeout and M105 missed parsing
some fix comes from @chepo92 PR that has not been merged in time to #52

**Comment by probonopd** [comment]
When the printer is idling, getting

```
> M105
< 
  39893
  free heap RAM: 36376

> M105
< 
  41893
  free heap RAM: 34776

> M105
< 
  43892
  free heap RAM: 33176

> M105
< 
  45892
  free heap RAM: 34776

> M105
< 
  47921
  free heap RAM: 36376

> M105
< 
  49893
  free heap RAM: 36376

> M105
< 
  51893
  free heap RAM: 36376

> M105
< 
  53893
  free heap RAM: 36376

> M105
< 
  55961
  free heap RAM: 36376

> M105
< 
  57892
  free heap RAM: 33176
```

Why is the printer not responding here? In https://github.com/probonopd/WirelessPrinting/pull/67#issuecomment-468437585 it is responding...

**Comment by GMagician** [comment]
Because I'm idiot...I added fix to this

**Comment by GMagician** [comment]
I'm thinking that timeout, when printing, should set error and stop...I'm think it can be too dangerous to continue

**Comment by probonopd** [comment]
Now getting

```
> M105
< ok T:33.4 /0.0 B:33.3 /0.0 T0:33.4 /0.0 @:0 B@:0

  51928
  free heap RAM: 36328

> M105
< ok T:33.5 /0.0 B:33.3 /0.0 T0:33.5 /0.0 @:0 B@:0

  53928
  free heap RAM: 36328

> M105
< ok T:33.4 /0.0 B:33.3 /0.0 T0:33.4 /0.0 @:0 B@:0
```

when the printer is idling but Cura still shows no temperatures and `/api/job` shows

```
{
  "state": {
    "text": "Operational",
    "flags": {
      "operational": true,
      "paused": false,
      "printing": false,
      "pausing": false,
      "cancelling": false,
      "sdReady": false,
      "error": false,
      "ready": true,
      "closedOrError": false
    }
  },
  "temperature": {
    "tool0": {
      "actual": 0.0,
      "target": 0.0,
      "offset": 0
    },
    "bed": {
      "actual": 0.0,
      "target": 0.0,
      "offset": 0
    }
  },
  "sd": {
    "ready": false
  }
}
```

**Comment by probonopd** [comment]
Yes :+1:

**Pull request merged**
