### PR TITLE
uniform coding style

### PR DESCRIPTION
**Pull request by GMagician**
Added indentation to includes
moved all include at beginning
uniformed some coding style

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks. Does it compile for you locally?

**Comment by GMagician** [comment]
I removed something by error, now locally it compiles

**Comment by probonopd** [comment]
Now it also compiles here 👍 

Did you test the resulting sketch, so that you know if really prints and does not crash? I am asking because I often compiled this sketch and then found out that it crashes when running it, even when I was doing innocent-looking changes.

**Comment by GMagician** [comment]
At the moment I programmed my d1 mini with original master complied code and I'm trying to configure wifi connection.
I want to connect it to my mega2560 but it's 5V and not 3.3V so I don't know how to proceed.
I would like to buy a new 32 bits card (ruramps4d/due or new all-in-one from ruramps4d producer but it will be ready in january/february) so I think I have to wait a long before really use it

**Comment by GMagician** [comment]
I'm doing a massive work on this program, I'll post something when tested.
Such work will include also this...

**Pull request closed without merging**
