### PR TITLE
M105 timeout fix with fw autotemp disabled

### PR DESCRIPTION
**Pull request by chepo92**

### CODE REVIEW

**Comment by GMagician** [comment]
I'm going to copy these from your original PR into #64

**Comment by probonopd** [comment]
When the printer is idling, getting

```
  51951
  free heap RAM: 33144

> M105
< ok T:67.9 /0.0 B:47.9 /0.0 T0:67.9 /0.0 @:0 B@:0

  53951
  free heap RAM: 36344

> M105
< ok T:67.4 /0.0 B:47.9 /0.0 T0:67.4 /0.0 @:0 B@:0

  55952
  free heap RAM: 32488

> M105
< ok T:66.9 /0.0 B:47.9 /0.0 T0:66.9 /0.0 @:0 B@:0

  57952
  free heap RAM: 36344

> M105
< ok T:66.5 /0.0 B:47.9 /0.0 T0:66.5 /0.0 @:0 B@:0

  59979
  free heap RAM: 36344

> M105
< ok T:66.0 /0.0 B:47.8 /0.0 T0:66.0 /0.0 @:0 B@:0

  61951
  free heap RAM: 36344
```

but Cura is not showing a temperature.

**Comment by GMagician** [comment]
@probonopd try #64 ad let me know

**Comment by probonopd** [comment]
Looks like we have 2 PRs addressing the same issue. To avoid this in the future, feel free to assign yourself to an issue before starting to work on it.

assign

Feels great to have progressed from a 1-person to a multi-person project :+1:

**Comment by chepo92** [comment]
> 
> 
> Looks like we have 2 PRs addressing the same issue. To avoid this in the future, feel free to assign yourself to an issue before starting to work on it.
> 
> assign
> 
> Feels great to have progressed from a 1-person to a multi-person project +1

This was a merge timeout LOL, I had solved (and PR'd) the issue before you found it. It was working yesterday, see if it does for you.

**Comment by probonopd** [comment]
As written in https://github.com/probonopd/WirelessPrinting/pull/67#issuecomment-468437585 it is halfway-working for me. The printer does respond with the temperature but it does not make its way into Cura.

**Comment by chepo92** [comment]
> 
> 
> Looks like we have 2 PRs addressing the same issue. To avoid this in the future, feel free to assign yourself to an issue before starting to work on it.
> 
> assign

I don't have the option to assign myself to issues, I think you have to add us as colaborators or something

**Comment by probonopd** [comment]
Sent collaborator invites.

**Comment by probonopd** [comment]
I think this can be closed in favor of 1740455?

**Pull request closed without merging**
