### PR TITLE
Change default baud rate to Marlin's 250k 

### PR DESCRIPTION
**Pull request by chepo92**
As Marlin is the most common firm this should be the default baud rate

### CODE REVIEW

**Comment by probonopd** [comment]
Strange, my printers also came with Marlin (one being the Prusa i3 MK2S) and as far as I remember they don't use 250k by default?

**Comment by chepo92** [comment]
Newest versions of marlin (i would say since 1.1.6) use 250k as default, although some old based firms and host still use 115200.
(https://reprap.org/wiki/Marlin). 

I can add some instructions on setting baudrate as it could be a common issue

**Comment by probonopd** [comment]
Yes, please add a paragraph on this. Did not know it. Thanks.

**Comment by probonopd** [comment]
Or even better, add auto-baudrate detection ;)

**Comment by probonopd** [comment]
Great commit now but please make the default 115200 since that is what 2 out of 2 printers I own use ;-)

**Comment by probonopd** [comment]
Thank you

**Pull request merged**
