### PR TITLE
Base Library

### PR DESCRIPTION
**Pull request by ayushsharma82**

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you. I think you wanted to send the PR to the library branch?

**Comment by probonopd** [comment]
Also, we need to adjust `.travis.yml` so that the PR builds green

**Comment by ayushsharma82** [comment]
Yeah.. My Mistake, I will send PR to library branch.

**Comment by probonopd** [comment]
Thanks, no problem. Now we need to get it to build on Travis CI. Does it build for you locally?

**Pull request closed without merging**
