### PR TITLE
Implement download, closes #78

### LINKED ISSUE #78: Implement /download
Implement `/download`, it should respond with the GCODE that was last stored.

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

**Comment by probonopd** [comment]
Trying to implement https://github.com/me-no-dev/ESPAsyncWebServer#respond-with-content-coming-from-a-file but I am not sure how to do this using StorageFS. Any clue @GMagician?

Getting

```
ESP8266WirelessPrintAsync:583:69: error: no matching function for call to 'AsyncWebServerRequest::send(StorageFS&, String&, const char [20])'
     request->send(storageFS, uploadedFullname, "application/x-gcode");
```

https://travis-ci.org/probonopd/WirelessPrinting/builds/500736473#L3336

**Comment by GMagician** [comment]
Yes storageFS will switch between spiffs and SD depending on which one is active...only issue I see is that "last used filename" logic when it scan unit, will report a file as a "previous loaded file" it should skip "firmware file" to avoid issues

**Comment by probonopd** [comment]
What am I doing wrong then in the snippet above?

**Comment by GMagician** [comment]
I think  is not to be done in "/api/files"...this I think should just report files in unit...but maybe i should read octoprint manuals before answert....

**Comment by probonopd** [comment]
Oh right, typo, I meant /download (this is for the link that we have on the HTML page, not OctoPrint related)

**Comment by GMagician** [comment]
mmm SPIFFS is stream derived class... FileWrapper is not...

**Comment by GMagician** [comment]
Maybe it must be checkd if SDFile is also derived from stream class. If both are then also FileFrapper may be derived from stream and works as you need

**Comment by probonopd** [comment]
> Maybe it must be checkd if SDFile is also derived from stream class. 

It seems that it is:
https://github.com/esp8266/Arduino/blob/master/libraries/SD/src/SD.h#L26

Now what do I do? Not use storageFS?

**Comment by GMagician** [comment]
If both spiFFS file and sdfile are derived from stream then alsow filewrapper should and since    request->send(...) needs a stream you have to pass object returned from storageFS.open

**Comment by GMagician** [comment]
but maybe the better is to check what `request->send` needs

**Comment by GMagician** [comment]
..example talk about  SPIFFS...but this is a class. to send a file I'm expecting an SPIFFS.file opbject..soruce code must be checked to see what it really need...if it is a stream we may derive FileWrapper from stream (implement all missing methods)

**Comment by probonopd** [comment]
So maybe I need to "respond with content coming from a Stream":
https://github.com/me-no-dev/ESPAsyncWebServer#respond-with-content-coming-from-a-stream

**Comment by probonopd** [comment]
Does not work either, build log: https://api.travis-ci.org/v3/job/500755530/log.txt

```
ESP8266WirelessPrintAsync.ino: In lambda function:
ESP8266WirelessPrintAsync:583:69: error: no matching function for call to 'AsyncWebServerRequest::send(StorageFS&, const char [20], long int)'
     request->send(storageFS, "application/x-gcode", gcodeFile.size());
                                                                     ^
```

**Comment by probonopd** [comment]
```
/home/travis/.arduino15/packages/esp8266/hardware/esp8266/2.5.0/cores/esp8266/Stream.h:38:7: note:   no known conversion for argument 1 from 'StorageFS' to 'const Stream&'
/home/travis/.arduino15/packages/esp8266/hardware/esp8266/2.5.0/cores/esp8266/Stream.h:38:7: note: constexpr Stream::Stream(Stream&&)
/home/travis/.arduino15/packages/esp8266/hardware/esp8266/2.5.0/cores/esp8266/Stream.h:38:7: note:   no known conversion for argument 1 from 'StorageFS' to 'Stream&&'
ESP8266WirelessPrintAsync:583:27: error: cannot allocate an object of abstract type 'Stream'
     request->send((Stream)storageFS, "application/x-gcode", gcodeFile.size());
                           ^
```

**Comment by probonopd** [comment]
This seems to be much harder than anticipated. It's a pity that we have to deal with low level stuff such as whether a file is stored on SD or SPIFFS. In my opinion, this should all be abstracted away by the [esp8266/Arduino](esp8266/Arduino) classes.

@earlephilhower said in 
https://github.com/esp8266/Arduino/issues/4740#issuecomment-392135052

> I've just created a generic File wrapper virtual base class and written SD or SPIFFS subclasses that can be passed back to the library to handle the work.

This is way over my head, but maybe we could use it?

**Comment by GMagician** [comment]
No it's almos easy....first you open file with storageFS.open. returned object (FileWrapper) should be passed to send method but first...FileWrapper must derive from Stream class

**Comment by probonopd** [comment]
I don't know what I need to do. Can you help with code?

**Comment by GMagician** [comment]
Well I would like to close critical issues before new feature...

**Comment by GMagician** [comment]
I'll open a new PR with FileWrapper subclassing...you may close this and continue on mine if necessary

**Pull request closed without merging**
