### PR TITLE
Added links to required libraries

### PR DESCRIPTION
**Pull request by chepo92**

### CODE REVIEW

**Comment by GMagician** [comment]
To pass Travis you hae to use file I posted in my PR. Here you have the problem I had (error compiling hash)

**Comment by GMagician** [comment]
I'm not sure but one thing @chepo92 changed in my PR to let zeroconfig works has been to add mdns.update call in main loop. This was not present in your original code and I suspect something has been changed in esp lib 2.5.0 (you used 2.3.3 beta in original project but travis doesn't compile anymore with it).

**Comment by GMagician** [comment]
@probonopd it may be that other PR (code rewamping) has done the "wrong" bin copy...for sure that code doesn't work yet!

**Comment by probonopd** [comment]
> for sure that code doesn't work yet!

Thanks for checking @GMagician.

**Comment by chepo92** [comment]
> 
> 
> Thanks for this PR.
> 
> Can someone confirm that the binary from https://transfer.sh/RlfTM/ESP8266WirelessPrintAsync_d1_mini_0579a01.bin actually works (you can print using it without crashing)? This binary was built and uploaded automatically for [1fd803f](https://github.com/probonopd/WirelessPrinting/commit/1fd803f58bebace13be09396746fda052d039610) using Travis CI.

Tested it, uploading gcode with cura crashes, web upload works

**Comment by probonopd** [comment]
Thanks for testing. We need to find out why it crashes with Cura.

**Comment by probonopd** [comment]
I think my version also crashes with Cura (at one point it did not do that - not sure what chaged; some code in the esp8266 core, in the libraries, or here).

So I think this is good to merge?

**Comment by probonopd** [comment]
Possibly we should skip this PR and go to https://github.com/probonopd/WirelessPrinting/pull/52 directly? I am trying to avoid merge conflicts.

**Comment by probonopd** [comment]
Closing in favor of #52. @chepo92 please send a new PR against master if you think something still needs to be changed.

**Pull request closed without merging**
